### ISSUE TITLE
HDR not working on Shield TV pro 2019

### ISSUE THREAD

**Issue by Bonk-Choy** [yuliskov/SmartYouTubeTV#390]
When choosing HDR in the quality settings, the video will freeze with the circle as if it is buffering.

Tried different resolutions, the problem remains the same.

Shield TV pro 2019 version. The app is the latest stable release, as of Dec 12 2019.

Thanks

**Comment by fgl27** [comment]
Probably the device doesn't support the codec used by YouTube... I assume is the same issue of the 2017 model.

 Last time I search about it Nvidia said was a hardware incapacity so no fix for the 2017 model..

I try on 2017 model to use exoplayer vp9 lib to decode YouTube hdr vp9 profile 2 but it gives a error and doesn't work.

Maybe the app can identify the available codecs and warns the user, not play the content avoiding issues like this.

**Comment by Bonk-Choy** [comment]
My Mi Box S cannot play HDR with the official YouTube app, but SmartYouTubeTV works perfectly on it.

I checked both devices' specs, and both support VP9:

https://www.nvidia.com/en-us/shield/shield-tv-pro/
https://www.mi.com/us/mi-box-s/specs

**Comment by fgl27** [comment]
HDR is not a simple vp9 option read again my post.

https://www.nvidia.com/en-us/geforce/forums/discover/280158/vp9-profile-2-software-update-/

Noting about vp9.2 on this link
https://www.nvidia.com/en-us/shield/shield-tv-pro/

**Comment by fgl27** [comment]
you can use this app to check codec info (as long you have a mouse)
https://play.google.com/store/apps/details?id=com.ellevsoft.mediacodecinfo&hl=en

the mi box s has the 
OMX.amlogic.vp9.decoder.awesome
and it has support for vp9 profile 0 and 2 up to level 5.1

But the Nvidia at least the 2017 model doesn't at least not on the hardware codec level, but on the software it has up to 1080p for hdr vpp profile 2 using the google vp9 codec... but for some reason doesn't work maybe because the level is only 5 or is a OS lock, it can be set to not be used by the maker of the device (Nvidia).

I can't screenshot the mibox so I shared the info I read, but I can in the nvidia the bellow is the screenshot of Nvidia shield 2017

![Media Codec Info_20191212_181401](https://user-images.githubusercontent.com/13755892/70750224-c29b6b80-1d0c-11ea-944e-d44cdb154002.png)

so what is the info for you on the 2019 model?

**Comment by Bonk-Choy** [comment]
Thanks for the information. I compared my Codec Info to yours and they're exactly the same.

If it's technically not possible, I'll close this issue.

**Comment by Bonk-Choy** [comment]
Same issue as the 2017 Shield TV

**Comment by fgl27** [comment]
I did some test just for context

using this hdr video
https://www.youtube.com/watch?v=tO01J-M3g0U

Download the hdr files and play using Kodi on the Nvidia 2017 model
the 4K and 1440p file play but is very very lag unwatchable, the 1080p plays somewhat OK some moments with a small lag some smoth...

Testing the mi box s the same files play no lag at all 4k 1440p and 1080p.
Just like playing the videos on SmartYouTubeTV selecting HDR 4K60 on the mi box

**Comment by fgl27** [comment]
quadrupled issue
https://github.com/yuliskov/SmartYouTubeTV/issues/242
https://github.com/yuliskov/SmartYouTubeTV/issues/315
https://github.com/yuliskov/SmartYouTubeTV/issues/390
https://github.com/yuliskov/SmartYouTubeTV/issues/573

can someone close those issue as makes no sense.
and can people be polite and stop open so many issues about the same thing.
