### ISSUE TITLE
Feature Request: Video preview

### ISSUE THREAD

**Issue by onlytanmoy** [yuliskov/SmartYouTubeTV#452]
Please can you implement the feature which shows the video preview? More details in link below.

https://support.google.com/youtube/answer/7074781?hl=en-GB

**Comment by mirkorobocop** [comment]
it would be great

**Comment by fgl27** [comment]
I think this is the featuring is already on the official version of the app, only on devices that support animation.

when this youtube app open it informs via 'user-agent' with device is running

https://github.com/yuliskov/SmartYouTubeTV/blob/new-exo-player/common/src/main/java/com/liskovsoft/smartyoutubetv/misc/UserAgentManager.java#L45

I don't know why is used a **lg webos** user agent maybe because a proper android one is not available, I hope @yuliskov can inform why?

I tried to make a android 'user agent' and didn't manage to make one that works on the new UI, even using the default user agent from my device it doesn't work the youtube Tv version of the youtube doesn't open using the default user agent of my device not on a browser not on the device... It seems google use a combination of they default base user agent (Cobalt/ something something) plus some information from the device itself...

one can test a user agent on a chrome browser and open https://www.youtube.com/tv

this is how to change it https://winaero.com/blog/change-user-agent-chrome/
![Screenshot from 2020-03-16 17-06-31](https://user-images.githubusercontent.com/13755892/76795743-bfe76100-67a8-11ea-8d5c-46600c40200c.png)

So if I use the one from 

https://github.com/yuliskov/SmartYouTubeTV/blob/new-exo-player/common/src/main/java/com/liskovsoft/smartyoutubetv/misc/UserAgentManager.java#L30

I have that preview animation but that agent is from the old UI so it probably will cause problem if use it.

If someone can find the proper new UI agent by testing it on chrome, we can update the app and even if some low end device can' t use it because they lag on animations, @yuliskov can just add a switch to enable disable it at start, disable by default to prevent issue on those devices...

So @yuliskov can you or anyone else help with this.

This also is a solution for https://github.com/yuliskov/SmartYouTubeTV/issues/368 and animation related issues.

**Comment by mirkorobocop** [comment]
@fgl27 thank you for explaining how it works
> If someone can find the proper new UI agent by testing it on chrome, we can update the app 

I found a user-agent with a new ui in which the thumbnail preview works, here it is:
`Mozilla/5.0 (Linux) Cobalt/11.119147-qa (unlike Gecko) Starboard/6, CVA_STB_BCM72604C0/KA99.00.17.09 (Arris, DCX4400, Wired)`

so we need only a few changes in the code, i.e. add this user-agent and add the thumbnail preview switch in the settings

**Comment by fgl27** [comment]
Nice find @mirkorobocop can you tell us how did you find it? for future reference in case it stops working for example.

I build the app from source using the agent share by @mirkorobocop and it work animations are enable also video preview and the option for "Press and Hold for More Options" als works

So it solves this issue, issue https://github.com/yuliskov/SmartYouTubeTV/issues/368 and https://github.com/yuliskov/SmartYouTubeTV/issues/436, so is a good thing as it solves 3 issues maybe more.

But it isn't OK for use yet there is a couple of bugs, so is something @yuliskov must look as I don't understand the app that well to fixe it.

bugs I notice:

1. some video don't play they are most music videos
2. on exit a video is needed to press back key twice for it to fully exit back to the browser, first click closes the player and the buffer/loading animation shows the second click shows the browser

there maybe other bugs will test furter if I find something else I post here...

**Comment by mirkorobocop** [comment]
@fgl27 
> can you tell us how did you find it?

unfortunately it was a lucky shot

first I sniffied traffic on my smartphone with the youtube for android tv app  looking for correct user-agent and it's looked like this:
`user-agent: com.google.android.youtube.tv/{app version}(Linux; U; Android {android version}; {language}; {smarphone model} Build/{rom build number?}) gzip`
but I noticed that the address being called is `youtubei.googleapis.com/youtubei/` and not `youtube.com/tv` 
then I just started googling the phrase cobalt+user-agent and there I found this page
[(https://developers.whatismybrowser.com/useragents/explore/operating_system_name/linux/](https://developers.whatismybrowser.com/useragents/explore/operating_system_name/linux/) 
where I found this user-agent that worked
![cobalt](https://user-images.githubusercontent.com/20727745/76917560-13020680-68c4-11ea-81c7-e44595236aed.png)

> bugs I notice:
> 
> 1. some video don't play they are most music videos
> 2. on exit a video is needed to press back key twice for it to fully exit back to the browser, first click closes the player and the buffer/loading animation shows the second click shows the browser

Looks like I was too happy, we have to dig deeper

**Comment by fgl27** [comment]
Nice...

I did some testing on user agents... if one replace the `AppleWebKit/537.1+` from https://github.com/yuliskov/SmartYouTubeTV/blob/new-exo-player/common/src/main/java/com/liskovsoft/smartyoutubetv/misc/UserAgentManager.java#L17 with just `Cobalt/11.0-qa` it just work and it can be anthing above 10.0 I try up to 40.0 50.0...

Unfortunately the bugs remain the same but the improves still there.

**Comment by mirkorobocop** [comment]
@yuliskov Do you have an idea how to solve it?

**Comment by fgl27** [comment]
Latest version of the app already have the featuring requested on this issue, plus hold enter for menus and I update issue https://github.com/yuliskov/SmartYouTubeTV/issues/368 with a workaround to enable the rest of the animations.

**Comment by onlytanmoy** [comment]
@fgl27 many thanks....very happy to see this feature implemented 😍

**Comment by fgl27** [comment]
> @fgl27 many thanks....very happy to see this feature implemented

BTW is all thanks to @yuliskov

**Comment by onlytanmoy** [comment]
okay :) thanks a lot @yuliskov awesome work 👌

**Comment by onlytanmoy** [comment]
@yuliskov I am so enjoying this new feature especially 'Add to watch later' functionality, super convenient...many thanks for this...closing this issue...stay safe mate.
